# all vlogs client instances configure a basic auth secret that is generated by the master stack
# for aggregated log select by vlselect
data "pxc_vlselect_auth" "vlselect_master" {
  mc_peers = local.mc_peers_set
  mc_token = local.mc_token
}

resource "kubernetes_secret" "basic_auth_secret_vlogs" {
  type = "Opaque"
  metadata {
    name = "basic-auth-vlogs"
    namespace = kubernetes_namespace.mon_ns.metadata[0].name
  }
  data = {
    "auth" : "vlogs:${bcrypt(data.pxc_vlselect_auth.vlselect_master.vlselect_auth_password)}"
  }
}

resource "pxc_cloud_secret" "vlogs_discovery" {
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs"
  secret_data = jsonencode({
    host = var.victorialogs_host
    k8s_stack_name = data.pxc_cloud_self.self.stack_name
  })
  secret_type = "vlogs-storage-node"
}

resource "pxc_helm_mirror" "vlogs" {
  source_repository = "https://victoriametrics.github.io/helm-charts/"
  source_name = "vmetrics"
  chart = "victoria-logs-single"
  version = "0.11.26"
}

resource "helm_release" "vlogs" {
  repository = pxc_helm_mirror.vlogs.repository_out
  chart = pxc_helm_mirror.vlogs.chart
  version = pxc_helm_mirror.vlogs.version
  name = "vlogs"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name
  create_namespace = true

  values = module.mon_shared.vl_single_config

  timeout = 1200
}

resource "pxc_helm_mirror" "vmalert" {
  source_repository = "https://victoriametrics.github.io/helm-charts/"
  source_name = "vmetrics"
  chart = "victoria-metrics-alert"
  version = "0.32.0"
}

resource "helm_release" "vmalert" {
  count = var.logging_only ? 0 : 1 # no alerts when flag is true
  repository = pxc_helm_mirror.vmalert.repository_out
  chart = pxc_helm_mirror.vmalert.chart
  version = pxc_helm_mirror.vmalert.version
  name = "vmalert"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name

  values = [
    <<-YML
      server:
      %{ if var.node_selector != null }
        nodeSelector:
          ${indent(4, yamlencode(var.node_selector))}
      %{ endif }
      %{ if var.tolerations != null }
        tolerations:
          ${indent(4, yamlencode(var.tolerations))}
      %{ endif }
        datasource:
          url: "http://vlogs-victoria-logs-single-server:9428"
        notifier:
          alertmanager:
            url: "http://kube-prometheus-stack-alertmanager:9093"
    YML
    , module.mon_shared.log_rules
  ]

  timeout = 1200
}

# when a client stack is supposed to monitor a proxmox cluster, all vms, lxcs and hosts use this discovery secret
# for setting up journald log aggregation through vector systemd
resource "pxc_cloud_secret" "vlogs_cluster_journald" {
  count = var.monitor_proxmox_cluster ? 1 : 0
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs-journald"
  secret_data = jsonencode({
    target_pve = data.pxc_cloud_self.self.target_pve # this becomes the vlogs database target for all
    basic_pw = data.pxc_vlselect_auth.vlselect_master.vlselect_auth_password
    host = var.victorialogs_host
  })
  secret_type = "vlogs-cluster-journald"
}
