# all vlogs client instances configure a basic auth secret that is generated by the master stack
# for aggregated log select by vlselect
data "pxc_cloud_secret" "vlogs_storage_node_pw" {
  secret_name = "${local.cluster_vars.pve_cloud_domain}-vlogs-storage-node"
}

# here we apply the same multi cloud logic as for gotify
data "http" "vlselect_auth" {
  # Convert the list to a set for for_each
  for_each = toset(local.mc_peers_set)

  url = "${each.value}/get-vlselect-auth"

  request_headers = {
    Authorization = "Bearer ${local.mc_token}"
    Accept        = "application/json"
  }
}

locals {
  mc_vlselect_master_filtered = [for peer, response in data.http.vlselect_auth : jsondecode(response.response_body) if jsondecode(response.response_body).auth_present ]
  vlselect_auth_password = data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data != "" ? jsondecode(data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data).password : local.mc_vlselect_master_filtered[0].vlselect_auth.password
}

check "multi_auth" {
 assert {
   condition     = (data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data != "" && length(local.mc_vlselect_master_filtered) == 0) || (data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data == "" && length(local.mc_vlselect_master_filtered) == 1)
   error_message = "Vlselect multiselect within cloud / multi cloud peers not properly configured! There should only be a instance deployed!"
 }
}


resource "kubernetes_secret" "basic_auth_secret_vlogs" {
  type = "Opaque"
  metadata {
    name = "basic-auth-vlogs"
    namespace = kubernetes_namespace.mon_ns.metadata[0].name
  }
  data = {
    "auth" : "vlogs:${bcrypt(local.vlselect_auth_password)}"
  }
}

resource "pxc_cloud_secret" "vlogs_discovery" {
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs"
  secret_data = jsonencode({
    host = var.victorialogs_host
    k8s_stack_name = data.pxc_cloud_self.self.stack_name
  })
  secret_type = "vlogs-storage-node"
}


resource "helm_release" "vlogs" {
  repository = "https://victoriametrics.github.io/helm-charts/"
  chart = "victoria-logs-single"
  version = "0.11.26"
  name = "vlogs"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name
  create_namespace = true

  values = module.mon_shared.vl_single_config

  timeout = 1200
}


resource "helm_release" "vmalert" {
  repository = "https://victoriametrics.github.io/helm-charts/"
  chart = "victoria-metrics-alert"
  version = "0.32.0"
  name = "vmalert"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name

  values = [
    <<-YML
      server:
      %{ if var.node_selector != null }
        nodeSelector:
          ${indent(4, yamlencode(var.node_selector))}
      %{ endif }
      %{ if var.tolerations != null }
        tolerations:
          ${indent(4, yamlencode(var.tolerations))}
      %{ endif }
        datasource:
          url: "http://vlogs-victoria-logs-single-server:9428"
        notifier:
          alertmanager:
            url: "http://kube-prometheus-stack-alertmanager:9093"
    YML
    , module.mon_shared.log_rules
  ]

  timeout = 1200
}

# when a client stack is supposed to monitor a proxmox cluster, all vms, lxcs and hosts use this discovery secret
# for setting up journald log aggregation through vector systemd
resource "pxc_cloud_secret" "vlogs_cluster_journald" {
  count = var.monitor_proxmox_cluster ? 1 : 0
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs-journald"
  secret_data = jsonencode({
    target_pve = data.pxc_cloud_self.self.target_pve # this becomes the vlogs database target for all
    basic_pw = local.vlselect_auth_password
    host = var.victorialogs_host
  })
  secret_type = "vlogs-cluster-journald"
}
