# all vlogs client instances configure a basic auth secret that is generated by the master stack
# for aggregated log select by vlselect
data "pxc_cloud_secret" "vlogs_storage_node_pw" {
  secret_name = "${local.cluster_vars.pve_cloud_domain}-vlogs-storage-node"
}

resource "kubernetes_secret" "basic_auth_secret_vlogs" {
  type = "Opaque"
  metadata {
    name = "basic-auth-vlogs"
    namespace = kubernetes_namespace.mon_ns.metadata[0].name
  }
  data = {
    "auth" : "vlogs:${bcrypt(jsondecode(data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data).password)}"
  }
}

resource "pxc_cloud_secret" "vlogs_discovery" {
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs"
  secret_data = jsonencode({
    host = var.victorialogs_host
    k8s_stack_name = data.pxc_cloud_self.self.stack_name
  })
  secret_type = "vlogs-storage-node"
}


resource "helm_release" "vlogs" {
  repository = "https://victoriametrics.github.io/helm-charts/"
  chart = "victoria-logs-single"
  version = "0.11.26"
  name = "vlogs"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name
  create_namespace = true

  values = module.mon_shared.vl_single_config

  timeout = 1200
}


resource "helm_release" "vmalert" {
  repository = "https://victoriametrics.github.io/helm-charts/"
  chart = "victoria-metrics-alert"
  version = "0.32.0"
  name = "vmalert"
  namespace = kubernetes_namespace.mon_ns.metadata[0].name

  values = [
    <<-YML
      server:
        datasource:
          url: "http://vlogs-victoria-logs-single-server:9428"
        notifier:
          alertmanager:
            url: "http://kube-prometheus-stack-alertmanager:9093"
    YML
    , module.mon_shared.log_rules
  ]

  timeout = 1200
}

# when a client stack is supposed to monitor a proxmox cluster, all vms, lxcs and hosts use this discovery secret
# for setting up journald log aggregation through vector systemd
resource "pxc_cloud_secret" "vlogs_cluster_journald" {
  count = var.monitor_proxmox_cluster ? 1 : 0
  secret_name = "${data.pxc_cloud_self.self.stack_name}.${data.pxc_cloud_self.self.target_pve}-vlogs"
  secret_data = jsonencode({
    target_pve = data.pxc_cloud_self.self.target_pve # this becomes the vlogs database target for all
    basic_pw = data.pxc_cloud_secret.vlogs_storage_node_pw.secret_data
    host = var.victorialogs_host
  })
  secret_type = "vlogs-cluster-journald"
}
